# Github action workflow that will minify JS files

name: Minify on Push
on: push
jobs:
    Minify:
        runs-on: ubuntu-latest
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
        -   uses: actions/checkout@v2
          
        -   name: Auto Minify
            uses: ./.github/workflows/auto-minify
            with:
                directory: 'source'
                output: 'minified_source'
          
            # Auto commits minified files to the repository
            # Ignore it if you don't want to commit the files to the repository 
        -   name: Auto committing minified files
            uses: stefanzweifel/git-auto-commit-action@v4.1.6
            with:
                repository: 'minified_source'
                commit_message: "Github Action: Auto Minified JS and CSS files"
                branch: ${{ github.ref }}
